fix this error:
2025-04-05 16:29:01.500  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Refresh token available, attempting to refresh before connecting
2025-04-05 16:29:01.501  4083-4083  UserSessionManager      com.nekkochan.onyxchat               D  Refreshing token using URL: https://10.0.2.2:443/api/auth/refresh
2025-04-05 16:29:01.501  4083-4083  ChatNotificationService com.nekkochan.onyxchat               D  WebSocket connection state changed: CONNECTING
2025-04-05 16:29:01.501  4083-4083  ChatNotificationService com.nekkochan.onyxchat               D  WebSocket connecting...
2025-04-05 16:29:01.524  4083-4098  UserSessionManager      com.nekkochan.onyxchat               E  Error refreshing token
                                                                                                    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                    	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:358)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1131)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1086)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:873)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:744)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:709)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:907)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:242)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:224)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.nekkochan.onyxchat.util.UserSessionManager.lambda$refreshToken$0$com-nekkochan-onyxchat-util-UserSessionManager(UserSessionManager.java:198)
                                                                                                    	at com.nekkochan.onyxchat.util.UserSessionManager$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
                                                                                                    	at java.lang.Thread.run(Thread.java:1119)
                                                                                                    Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:665)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:542)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:498)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:346)
                                                                                                    	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:95)
                                                                                                    	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:169)
                                                                                                    	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:286)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1635)
                                                                                                    	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2025-04-05 16:29:01.524  4083-4098  UserSessionManager      com.nekkochan.onyxchat               E  	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:571)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1092)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1076)
                                                                                                    	... 25 more
                                                                                                    Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                    	... 39 more
2025-04-05 16:29:01.525  4083-4098  WebSocketClient         com.nekkochan.onyxchat               W  Failed to refresh token, will continue with current token

And after a while, the service has killed and when it happen, these stuff will show:

2025-04-05 16:30:01.146  4083-4083  ChatNotificationService com.nekkochan.onyxchat               D  Destroying Chat Notification Service
2025-04-05 16:30:01.148  4083-4101  WebSocketClient         com.nekkochan.onyxchat               D  WebSocket closing gracefully: code=1000, reason=Closed by client
2025-04-05 16:30:01.148  4083-4101  WebSocketClient         com.nekkochan.onyxchat               D  Scheduling reconnect attempt 1 with delay 2000ms
2025-04-05 16:30:01.148  4083-4101  WebSocketClient         com.nekkochan.onyxchat               D  WebSocket closed gracefully: code=1000, reason=Closed by client
2025-04-05 16:30:03.149  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Executing scheduled reconnect, attempt 1
2025-04-05 16:30:03.149  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Auth token starts with: eyJhbGciOi...
2025-04-05 16:30:03.149  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Connecting to WebSocket URL: wss://10.0.2.2:443/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDY0MWQ3ZS1hODllLTQ1Y2UtYTlhMS0zY2Y2MGJjNTZlMmQiLCJpYXQiOjE3NDM4NDUwNDEsImV4cCI6MTc0Mzg0ODY0MX0.Y8oyeSFjl5tzNaAOHJ92co6UbsN3zhzWSZjnxGb4lO0
2025-04-05 16:30:03.156  4083-4101  WebSocketClient         com.nekkochan.onyxchat               D  WebSocket connection opened
2025-04-05 16:30:03.157  4083-4101  WebSocketClient         com.nekkochan.onyxchat               D  WebSocket message received: {"type":"CONNECTION_ESTABLISHED","data":{"connectionId":"486044dc-cb1e-4de1-9840-88a45e61adcc","userId":"6d641d7e-a89e-45ce-a9a1-3cf60bc56e2d"}}
2025-04-05 16:30:06.153  4083-4101  WebSocketClient         com.nekkochan.onyxchat               E  WebSocket error: Software caused connection abort, code: 0, response: null, body:
                                                                                                    URL: unknown
                                                                                                    Headers: unknown
                                                                                                    java.net.SocketException: Software caused connection abort
                                                                                                    	at java.net.SocketInputStream.socketRead0(Native Method)
                                                                                                    	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:173)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:994)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:958)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:873)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:846)
                                                                                                    	at okio.InputStreamSource.read(JvmOkio.kt:90)
                                                                                                    	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
                                                                                                    	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                                                                                                    	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                                                                                                    	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
                                                                                                    	at java.lang.Thread.run(Thread.java:1119)
2025-04-05 16:30:06.153  4083-4101  WebSocketClient         com.nekkochan.onyxchat               D  Scheduling reconnect attempt 1 with delay 2000ms
2025-04-05 16:30:08.155  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Executing scheduled reconnect, attempt 1
2025-04-05 16:30:08.155  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Auth token starts with: eyJhbGciOi...
2025-04-05 16:30:08.155  4083-4083  WebSocketClient         com.nekkochan.onyxchat               D  Connecting to WebSocket URL: wss://10.0.2.2:443/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDY0MWQ3ZS1hODllLTQ1Y2UtYTlhMS0zY2Y2MGJjNTZlMmQiLCJpYXQiOjE3NDM4NDUwNDEsImV4cCI6MTc0Mzg0ODY0MX0.Y8oyeSFjl5tzNaAOHJ92co6UbsN3zhzWSZjnxGb4lO0

We can see that our service trying to alive, but not succeeded!

We already take all action: Reduce memory, etc. But system still kill it!

I read about that: @https://stackoverflow.com/questions/12219249/background-service-getting-killed-in-android

And one of answer make me attention to:

+50

The main problem is that we cannot say

    Services are not meant to be killed. They are meant to run in background as long as we want it to.

Basically, that is not true. System still can terminate the service in low memory and possibly other situations. There are 2 ways to overcome this:

    If you are implementing the service, override onStartCommand() and return START_STICKY as the result. It will tell the system that even if it will want to kill your service due to low memory, it should re-create it as soon as memory will be back to normal.
    If you are not sure 1st approach will work - you'll have to use AlarmManager http://developer.android.com/reference/android/app/AlarmManager.html . That is a system service, which will execute actions when you'll tell, for example periodically. That will ensure that if your service will be terminated, or even the whole process will die(for example with force close) - it will be 100% restarted by AlarmManager.

And in the comment section, we can see:

Q: If that is not always true, then what about the background services of music players, yahoo mail, facebook etc. They never get killed.
A:  Please check this method - @https://developer.android.com/reference/android/app/Service.html#startForeground  As described, heavy services that are running major user features like music playing - can startForeground() - and the system will try not to stop it. But you'll need to provide a notification to show user that background service is working. Also, there is still no guarantee that the system will not stop it, but it's much less probable.

And in the link has mentioned: @https://developer.android.com/reference/android/app/Service.html#startForeground , an paragraph said:

"A Service is an application component representing either an application's desire to perform a longer-running operation while not interacting with the user or to supply functionality for other applications to use. Each service class must have a corresponding <service> declaration in its package's AndroidManifest.xml. Services can be started with Context.startService() and Context.bindService().

Note that services, like other application objects, run in the main thread of their hosting process. This means that, if your service is going to do any CPU intensive (such as MP3 playback) or blocking (such as networking) operations, it should spawn its own thread in which to do that work. More information on this can be found in Processes and Threads. The JobIntentService class is available as a standard implementation of Service that has its own thread where it schedules its work to be done."